Squashed commit of the following:
commit 2b6e1e299fe72b7cc6fac86584c6526d7d4521f5
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jul 30 10:33:17 2022 +0300

    remove old implementation of the docgen_ast_aux

commit ad18206d378c0a9a4415caae509b62b8e119f04e
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Jul 3 00:24:42 2022 +0300

    get values from enum literal

    - compiler/ast/ast_types.nim:929 :: enum field does not store
      'position', it stores a 'value'. Maybe this was lost in translation
      somewhere, although apparently this code dates back as far as nim
      0.8.5 (BTW it was left in the "regular comment, not a documentation
      one" for all these years, because apparently using language feature
      and tooling is beneath the notice of a compiler developer(s))

commit 0cef027b27fc710aa3abb7d0a815ca9565097aa5
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jul 2 23:32:33 2022 +0300

    missing uses of the `trfShowTypeSym`&co

    some of the flags for AST representation were defined but weren't
    checked for, resulting in unconditionally generated noise. Fixes in this
    commit, along with some other minor output cleanups (debugging in
    progress). Also print symbol names as string in quotes if more verbose
    option is not enabled.

commit 214684c0c39f8ccbca2067e1b2177818f37c1e88
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jul 2 23:09:00 2022 +0300

    optionally show symbol symbol type for one level

commit 2bcdf1cf449db16c92235fde0e35194120f445b1
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jul 2 22:30:08 2022 +0300

    more astrepr improvements

    trying to register enum value ranges from the literals: so far had
    varying success, but hopefully will fix it sooner or later.

commit 75d3d4dcafe20a1c125b67e7436a13e1749c58e0
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jul 2 17:34:00 2022 +0300

    'fix' side effect annotations on the text layouter

commit 5acc6bd8d15726bc0f8bdd725c5638f76227a562
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 23:39:31 2022 +0300

    docs

commit b2270245e7ab2d4ecb6eafb1cbe13487a75e9c54
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 23:29:07 2022 +0300

    documentation registration high-level overview

commit 674cf0b308eec70f063e6e1d23aebf1217bf37dd
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 23:05:12 2022 +0300

    more implementation documentation

    Add more documentation for the implementation fields. Remove `DocIdent`
    and other leftovers from the haxdoc code.

commit d2fd060386b4da7f0e5c735d91de865a0d94cbfa
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 22:58:01 2022 +0300

    format RST lists to appease github rendering

commit 3bdf1d18bd200743047bf9fcf5559396cdfa1067
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 22:52:06 2022 +0300

    note about extra documentation processing

commit df5de0b38f652f271a0767abcc4c9cad49a6d1ec
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 21:49:30 2022 +0300

    added RST->JSON conversion for the documentation

    Apparently implements https://github.com/nim-lang/RFCs/issues/447

    Generated documentation database has a `docs.tree` field that contains
    post-processed RST tree (so user does not have to deal with ~7 ways of
    defining links that rstast came up with, or another half a dozen ways to
    structure text into paragraph).

commit bbdd3e316100570ac59e7955df92176bfdec442e
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 19:52:44 2022 +0300

    more documentation for docgen

commit b6b8e9637ebfa09f8c89a57994eabcf142d8e86a
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 19:31:43 2022 +0300

    more RST AST normalization

commit 975f0185a3d2e277531abdc18b9cc26e82b2730d
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 18:03:03 2022 +0300

    database re-reading in a separate file, as example

commit c80945346ca3a07398c63b2e2d3b8e43180be045
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 16:48:32 2022 +0300

    fix post-rebase compilation errors

    I think I messed up rebase a little, so there were multiple compilation
    errors. Hopefully I didn't break the implementation too much (not really
    sure about that though, so it is important to keep in mind that some of
    the changes might've actually been unintentional).

commit d34929923767f4a6581ba1b5a0597118b5e6ff4d
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jun 18 16:12:10 2022 +0300

    Initial documentation for the database structure

commit 56b5c4041ac0e193f0227023669c86ddf694e1f3
Author: haxscramper <haxscramper@gmail.com>
Date:   Fri Jun 3 16:24:19 2022 +0300

    extract object and field documentation

commit b9fceb320289191abbdb4299f78d4ee9e2b486bd
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun May 29 15:47:00 2022 +0300

    docgen printing cleanup

commit c6eeae54fd4e1365d9e9cfc029898abf4d39b366
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat May 28 18:56:37 2022 +0300

    minor documentation update

commit 822235b3572f93b45d640990be4d4459c2efe488
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Mar 13 14:00:43 2022 +0300

    test: try using nimja to generate HTML docs

commit bcd7d0595dad1bcfbc9bcc079a6e8b7b29c686f1
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Mar 13 01:25:14 2022 +0300

    leftover implementation fixes

    documentation generator can now generate documentation for the whole
    project as well. Logic is hardcoded now, so if you want to try it out,
    you can use `nim doc file.nim` and it will dump every possible entry -
    sqlite, flat dump, json (POC for now) etc. For now documentation
    generator requires `--define=useNodeIds` to be set. In the future
    Data-Oriented node IDs will be reused.

    For sourcetrail database generation you would need to use
    `./compiler/tools/gentrail` with absolute path to the generated sqlite
    database. `gentrail` itself must be compiled separately, using C++
    backend, and depends on the compiler `SourcetrailDB` library that is
    provided in the `external/` subdirectory.

commit f099e4107331c17ae112ee2ee0ff9576d737c0ea
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Mar 9 00:45:26 2022 +0300

    more code processing bugfixes

commit 44aac96bb35dc4b2db8fdb2959f65a8ff0ea7667
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Mar 8 22:43:38 2022 +0300

    store parsed RST AST in the database

commit 4339a53e92f26746f9680504adeed49d85a00a6c
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 27 13:46:13 2022 +0300

    fix compilation errors after rename

commit 0d7a483318870e9c09724d7b810a906fae81329b
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 27 13:31:31 2022 +0300

    script to generate sourcetrail database

commit f0b3046121583b66c08c33c425191a8c5938878c
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 27 11:20:18 2022 +0300

    code formatter fixes

commit 5728676baeb69beb8b37d39586fdce60cc40487e
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Feb 21 17:47:34 2022 +0300

    Code renderer fixes

commit 4d20441b23683a5893d786ee76792428f85a6d4e
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 13 22:21:53 2022 +0300

    checkpoint

commit cbab1228d2fe04486f9461122e3bd98d5afc19c6
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 13 18:14:27 2022 +0300

    remove exported/maybe exported info

    information about module imports and exports is already present in the
    occurence information, so there is no need to explicitly duplicate it.

commit 782d6a4602ffb51cfb2ef0a779de7e2c871b8928
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 13 17:24:47 2022 +0300

    register uses in imports

commit 1ad07c1ed1d4d336249431b510f78c7faceeb7e5
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 13 16:40:11 2022 +0300

    make DocVisitor.parent non-optional

commit f7c6cd55bb06c8ed982f9da7e586ff8ba1074e63
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 13 16:34:58 2022 +0300

    fixed local ident registration for sourcetrail

commit 2b0bf94d44f63cd259ed43f7d584f4ca3076018f
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 13 14:29:41 2022 +0300

    sourcetrail registration seems work work for the most part

commit 38350e1039acaad5d1cbe4c0f4393d3578753758
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Feb 12 22:58:17 2022 +0300

    wip. make 'user' mandatory for occurencies

    Remove another layer of needless branching by making data collection
    requirements stricter.

commit e6ed521dceaa7f0d14df2b5b57f32e7c5f6b5626
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Feb 12 18:12:30 2022 +0300

    hack symbol registration data

commit 272e2f072e06e6631a900aa8b4491a01132623f3
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 9 22:16:29 2022 +0300

    checkpoint

commit c99a1255347615d6d723b79b80c62d522dbb38a0
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 9 17:52:14 2022 +0300

    checkpoint

commit cf8ad40bdf59293fcc0b98fb70bec223d79262d6
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 9 14:00:41 2022 +0300

    normalized alias/distinct handing

    removed `.isDistinct` field from the `DefTree` and added new defintion
    tree kind instead, flattening several conditions and cleaning up overall
    handling logic.

commit 55b4ce29ea174112dba1cd9de08738dbe781f0fa
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 9 12:09:22 2022 +0300

    clean up `occur` overloads

commit 6b60725e53f56b66cd1aa3d2a201eed39aaa398c
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Feb 8 22:42:48 2022 +0300

    garbage

commit 6a6e8c57d736706be28c12faedaf91c81620f621
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Feb 7 23:11:16 2022 +0300

    allow generating db only for a single target file

    previously, documentation database was genrated for a whole project at
    once, but now `--docMode=onefile` allows to narrow it down to input file
    only. This is necessary to simplify the debugging - without it
    `system.nim` is also implicitly processing, bringing total number of
    documentable entries to ~5k

commit 4bfc4c0cde3bcc0b483e4ca1dd6482dc5f0811ac
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Feb 7 15:54:55 2022 +0300

    roundtrip for documentation database via sqlite

commit d911ad7f4c57911bcd43b1667d94bc51e581e537
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Feb 7 14:42:26 2022 +0300

    write extents in sqlite database

commit e57420cfe53b7383ceb5c057edc65f6e841e2516
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Feb 7 14:09:16 2022 +0300

    store code extents in the separate table

    - store DocCodeLocation and DocExtent in separate table
    - Move DocContext type declaration to `docgen3`, all supplementary
      modules use DocDb
    - sourcetrail wrapper compiles properly

commit 578bb1a327dc244736d346d3f07f1a319bef24b0
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Feb 7 01:37:53 2022 +0300

    using sourcetrail writer directly

commit e960a824375c15df1aa82b63a7f337d260928ffc
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 6 23:05:43 2022 +0300

    checkpoint before deleting sourcetrail writer try

commit 1b3733bbfaf1b235e55a363428285f475491def7
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 6 19:34:25 2022 +0300

    sourcetrail writer improvements

commit d9809c479200008a49e783381d191144f992f4ce
Author: haxscramper <haxscramper@gmail.com>
Date:   Sun Feb 6 11:52:07 2022 +0300

    move entry signature construction to separate proc

commit e3a5291d65b173efcb78ab863e4eb12bed240a91
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Feb 5 21:10:16 2022 +0300

    checkpoint

commit 662c405b6528094eb3ff1d9d936b52b336e7967f
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Feb 5 19:46:51 2022 +0300

    wip: write sourcetrail database directly from docgen

commit 276d746dbe1f17a3750789c2e86b44eb3a9d3f0b
Author: haxscramper <haxscramper@gmail.com>
Date:   Fri Feb 4 23:25:13 2022 +0300

    generate sqlite database for the doc db

    generation of the sqlite database will allow to run some basic analysis,
    like tracking down all call paths from particular range of of code,

    select occur_of from occurencies
    where kind == A and X < loc_line and loc_line < Y

    then recursively iterating list of target calls. There are quite a few
    relations like one-to-many, so encoding them might be a little annoying
    for now.

commit 0682195a44a498dbe5e38f1a063115283cec2c2a
Author: haxscramper <haxscramper@gmail.com>
Date:   Fri Feb 4 22:45:57 2022 +0300

    documentation comment retrieval improvements

    - Add missing documentation comments for fields, procedures, enum
      fields.
    - store toplevel documentation comments for module, implement support
      for in-body documentation handling.
    - Add signatures to registered procedures in bodies

commit d966f9eab7206c392f39367e1a4f0f1555dbd1d3
Author: haxscramper <haxscramper@gmail.com>
Date:   Fri Feb 4 00:05:36 2022 +0300

    docgen: generate json dump of the database

commit 4413bf230d1388d2731f1c1c22935a067cc4abc5
Author: haxscramper <haxscramper@gmail.com>
Date:   Thu Feb 3 23:52:45 2022 +0300

    docgen: generate etags file table for the project

commit 59d2a160da3539cbd6e01141963278da0d9b203b
Author: haxscramper <haxscramper@gmail.com>
Date:   Thu Feb 3 23:17:33 2022 +0300

    .

commit 1a7a7540d288537a9da89f6f93c42ba2358c349a
Author: haxscramper <haxscramper@gmail.com>
Date:   Thu Feb 3 22:18:28 2022 +0300

    minor bugfixups

    - check for `skExported` in the 'unparseName' - there are no postfixes
      in the post-sem analysis
    - new usage kind - 'expansion'
    - add information about pre/in-sem documenter context, write it to the
      dump as well.

commit e460b787593b0a52af109abebb2291a24d007eb6
Author: haxscramper <haxscramper@gmail.com>
Date:   Thu Feb 3 21:44:20 2022 +0300

    write flat dump of the database for debugging

commit 1f3a7f6cadbc04f96748c2c5770c5320d5cc5638
Author: haxscramper <haxscramper@gmail.com>
Date:   Thu Feb 3 20:59:18 2022 +0300

    store location information directly in occur

commit f1e43d89176a06e31ed2f128a4a379ff46bd4fe7
Author: haxscramper <haxscramper@gmail.com>
Date:   Thu Feb 3 19:03:30 2022 +0300

    [CHECKPOINT]

commit df43b23622da51ceef444d1317efe791142f3b19
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 2 23:03:02 2022 +0300

    register untyped usage information

commit fc235d8d841273f09766df2148f0e9b5f5f923b2
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 2 22:23:31 2022 +0300

    register declarations in the pre-sem pass

    I think with current implementation there is no real need for separate
    PR like https://github.com/nim-works/nimskull/pull/214 - it can be
    trivially implemented from the documentation generator data via 'using'
    information.

commit cb6bfdf34d60feb5dc19634e08e6bf23a3bf2278
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 2 21:29:02 2022 +0300

    wip: pre-sem documenter context

commit 08150a58998e3d6d94d5c02e02c882858e976002
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 2 21:01:40 2022 +0300

    docgen: Update type documentation

commit 70e6eea4cbfaef27407b6d99ade8d8a1f3a3a7e3
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Feb 2 18:49:20 2022 +0300

    data: transition documentable entry store to DOD

    Transition documentable store implementation to use DOD as well - now
    `DocDb` stores absolutely all information required and entries are not
    randomly scattered around. This would make it easier to implement DB
    diffing, incremental documentation generation (if we ever need one).

    Documentable occurencies are also stored in the database now.

commit 83a9cea8ed6d88d34f161fac52479e2c658e09dc
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Feb 1 22:00:39 2022 +0300

    Can generate macro expansion printouts with occur

commit b85cdc3aa071e237b6dc8d5e15c48393ea830c95
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Feb 1 16:58:16 2022 +0300

    [CHECKPOINT]

commit 7902397fa32e5ee10647c68092405749ec6b5137
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Feb 1 14:48:22 2022 +0300

    code renderer

commit def432d6cf6a6a93050726141bd04146b3911631
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Feb 1 01:09:24 2022 +0300

    [WIP] Code formatter cleanup progress

commit 396265b881dfd592d974d08810452f44c410c587
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Jan 31 23:53:37 2022 +0300

    [WIP] Docgen code renderer implementation

commit 304fd38e530cc4dd9f6c2e153c0e5884acad249d
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Jan 31 22:28:34 2022 +0300

    text layouter compiles

    `strictEffects` flag is currently still insanely broken, it found mutations
    in all the changed procs, even ones where I pass enum as an argument, or
    ones where I read the sequence.

commit e2334df5407e24354fc7f330268df2cd648373f4
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Jan 31 21:50:13 2022 +0300

    Can print full expansion information

commit 9893342ab6e0b063737235b6c2fbd80fa90a8122
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Jan 31 21:11:12 2022 +0300

    Store the original node for occurencies

commit 92ebba66867d6618f4b816edbbeced21ed4d4977
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Jan 31 20:29:54 2022 +0300

    [CHECKPOINT] Ignore nodes that come from macro

commit 0b09ff17dae7784cc1be89b77be103ae586d1cbc
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Jan 31 20:19:22 2022 +0300

    [CHECKPOINT]

commit 0167021cfa2a6a73f7dee726e9e19cdeabcd44b7
Author: haxscramper <haxscramper@gmail.com>
Date:   Mon Jan 31 14:22:16 2022 +0300

    [CHECKPOINT] Add layouter

commit eace41751c3d3e33b29450579bc8ab713c3e33c2
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jan 29 23:58:48 2022 +0300

    [CHECKPOINT]

commit 08ca203b9b4967c978af8046e6739d96ebe9b348
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jan 29 19:56:41 2022 +0300

    [CHECKPOINT]

commit 03ddb434a7549001c45ed5b3d06d079158badd44
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jan 29 18:43:39 2022 +0300

    [CHECKPOINT]

commit ba0a4ce3d4294e67463d0f46ecb354c752839069
Author: haxscramper <haxscramper@gmail.com>
Date:   Wed Jan 19 00:02:06 2022 +0300

    register nested macro expansions

commit 9baf23736d92ee123b26b2ea7bc3a6e81300e387
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Jan 18 22:07:06 2022 +0300

    [CHECKPOINT] docgen compiles and runs

commit a93714f41341a9eb9d47655f2f1b24b77b291181
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Jan 18 19:42:43 2022 +0300

    [CHECKPOINT]

commit 09c1da3aec4d1f70db7f93f48fe9c1c02a6480e9
Author: haxscramper <haxscramper@gmail.com>
Date:   Tue Jan 18 00:31:53 2022 +0300

    [CHECKPOINT]

commit 9be586542067bc4283a3eacfe345610c729d845a
Author: haxscramper <haxscramper@gmail.com>
Date:   Sat Jul 2 10:19:20 2022 +0300

    [CHECKPOINT]